version: '3.8'

services:
  mongo:
    image: mongo
    container_name: expense-mongoDocker
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: expense-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/expense_db
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: expense-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
