name: CI - React Frontend Test & Build

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        working-directory: ./frontend

      - name: Lint & Build
        run: |
          npm run lint || echo "Lint errors, ignoring for now"
          npm run build
        working-directory: ./frontend
